#!/bin/bash
#
# ARG_OPTIONAL_SINGLE([project_tcl],[t],[Recreate project using the given .tcl script],[complex002.tcl])
# ARG_OPTIONAL_SINGLE([project_name],[n],[Recreate project under the given name instead of using the tcl script name])
# ARG_OPTIONAL_BOOLEAN([force],[f],[Overwrites any existing project with the same name],[off])
# ARG_OPTIONAL_SINGLE([vivado_path],[p],[Use the vivado version in [vivado_path]],[/Xilinx/Vivado/])
# ARG_OPTIONAL_SINGLE([vivado_version],[v],[Use the given vivado version in [vivado_path]],[2024.1])
# ARG_HELP([Recreates the Vivado project based on a .tcl script created by Vivado with \"write_project_tcl\".\n])

# DEFINE_SCRIPT_DIR([])

# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='tnfpvh'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_project_tcl="complex002.tcl"
_arg_project_name=
_arg_force="off"
_arg_vivado_path="/Xilinx/Vivado/"
_arg_vivado_version="2024.1"


print_help()
{
	printf '%s\n' "Recreates the Vivado project based on a .tcl script created by Vivado with \"write_project_tcl\".
"
	printf 'Usage: %s [-t|--project_tcl <arg>] [-n|--project_name <arg>] [-f|--(no-)force] [-p|--vivado_path <arg>] [-v|--vivado_version <arg>] [-h|--help]\n' "$0"
	printf '\t%s\n' "-t, --project_tcl: Recreate project using the given .tcl script (default: 'complex002.tcl')"
	printf '\t%s\n' "-n, --project_name: Recreate project under the given name instead of using the tcl script name (no default)"
	printf '\t%s\n' "-f, --force, --no-force: Overwrites any existing project with the same name (off by default)"
	printf '\t%s\n' "-p, --vivado_path: Use the vivado version in [vivado_path] (default: '/Xilinx/Vivado/')"
	printf '\t%s\n' "-v, --vivado_version: Use the given vivado version in [vivado_path] (default: '2024.1')"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-t|--project_tcl)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_project_tcl="$2"
				shift
				;;
			--project_tcl=*)
				_arg_project_tcl="${_key##--project_tcl=}"
				;;
			-t*)
				_arg_project_tcl="${_key##-t}"
				;;
			-n|--project_name)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_project_name="$2"
				shift
				;;
			--project_name=*)
				_arg_project_name="${_key##--project_name=}"
				;;
			-n*)
				_arg_project_name="${_key##-n}"
				;;
			-f|--no-force|--force)
				_arg_force="on"
				test "${1:0:5}" = "--no-" && _arg_force="off"
				;;
			-f*)
				_arg_force="on"
				_next="${_key##-f}"
				if test -n "$_next" -a "$_next" != "$_key"
				then
					{ begins_with_short_option "$_next" && shift && set -- "-f" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
				fi
				;;
			-p|--vivado_path)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_vivado_path="$2"
				shift
				;;
			--vivado_path=*)
				_arg_vivado_path="${_key##--vivado_path=}"
				;;
			-p*)
				_arg_vivado_path="${_key##-p}"
				;;
			-v|--vivado_version)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_vivado_version="$2"
				shift
				;;
			--vivado_version=*)
				_arg_vivado_version="${_key##--vivado_version=}"
				;;
			-v*)
				_arg_vivado_version="${_key##-v}"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}

parse_commandline "$@"

# OTHER STUFF GENERATED BY Argbash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || die "Couldn't determine the script's running directory, which probably matters, bailing out" 2

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


### CHECK REQUIREMENTS ###
if ! hash basename 2>/dev/null; then
    die "ERROR - This script requires the 'basename' command, which seems not to be present on your system."
fi

### ARGUMENT VALIDATION ###
# Add script dir path to default project tcl arg
if [[ "$_arg_project_tcl" == "complex002.tcl" ]]; then
    project_tcl=${script_dir}"/"${_arg_project_tcl}
else
    project_tcl=$_arg_project_tcl
fi
## Check if project tcl script exists
if [[ ! -f $project_tcl ]]; then
    die "ERROR - Project tcl script does not exist. Please give a valid path using the --project_tcl argument: $project_tcl"
fi

# Construct vivado settings path and source settings script
## Check if given vivado path exists
if [[ ! -d $_arg_vivado_path ]]; then
    die "ERROR - Vivado path does not exist. Please give a path to a valid Vivado installation: $_arg_vivado_path"
fi
## Check if given version exists in vivado path
vivado_path=${_arg_vivado_path}"/"${_arg_vivado_version}
if [[ ! -d $vivado_path ]]; then
    die "ERROR - Vivado version does not exist in vivado_path. Please give a valid Vivado version: $vivado_path"
fi
## Check if settings file exists
vivado_path=${vivado_path}/settings64.sh
if [[ ! -f $vivado_path ]]; then
    die "ERROR - No settings file found in Vivado installation. Please make sure it exists: $vivado_path"
fi
source $vivado_path

# Determine project name
if [[ "$_arg_project_name" != "" ]]; then
	project_name=$_arg_project_name
else
	project_tcl_name=$(basename $project_tcl)
	project_name=${project_tcl_name:0:(-4)} # Remove .tcl ending
fi

# Process force flag
if [[ "$_arg_force" == "on" ]]; then
    target_dir=${script_dir}/projects/${project_name}
    # Check if target project dir actually exists
    if [[ -d $target_dir ]]; then
        echo "WARNING - Target project dir exists and will be overwritten: $target_dir"
        read -p "Are you sure? (yes/no): " force
        if [[ "$force" == "yes" ]] || [[ "$force" == "y" ]]; then
            # Delete target project - this is final and happens even if the creation of the new project fails for other reasons!
            rm -r $target_dir
        else
            die "Aborted due to already existing target dir"
        fi
    fi
fi

### MODIFY PROJECT TCL ###
# Change root dir to location of project tcl instead of current working dir
sed -i 's/set origin_dir "."/set origin_dir [file dirname [info script]]/' $project_tcl
# Change project dir to ../projects/<project> instead (.. relative to origin dir)
sed -i 's/create_project ${_xil_proj_name_} .\/${_xil_proj_name_}/create_project ${_xil_proj_name_} $origin_dir\/..\/projects\/${_xil_proj_name_}/' $project_tcl

### CREATE PROJECT ###
vivado  -nolog -nojournal -mode batch -source $project_tcl -tclargs "--project_name" $project_name #"--origin_dir "

printf "\nFinished creating project!\n"
if [[ ! "$project_name" == "" ]]; then printf "Name: ${project_name}\n"; fi
if [[ ! "$target_dir"   == "" ]]; then printf "Dir:  ${target_dir}\n\n"; fi

# ] <-- needed because of Argbash